### ISSUE TITLE
Not working change of user

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#11]
![immagine](https://user-images.githubusercontent.com/47892201/109833354-7dc96080-7c41-11eb-8a23-24dd57896173.png)

**Comment by rgsax** [comment]
Se un professore è l'unico professore di quel corso non potrà cambiare ruolo, altrimenti non ci sarebbero più professori e nessun altro potrebbe cambiare ruolo. Deve essere ancora implementato il sistema di notifica che avvertirà che il professore non potrà cambiare il suo ruolo per il motivo descritto sopra.
