### ISSUE TITLE
Only one button for this

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#12]
![immagine](https://user-images.githubusercontent.com/47892201/109833426-8b7ee600-7c41-11eb-9ee0-ca66b578e897.png)

**Comment by sim55649** [comment]
![immagine](https://user-images.githubusercontent.com/64262053/110024018-21903a80-7d2e-11eb-987f-fa0921b758b0.png)

I propose this solution, to avoid confusion with the talk about having a single button.
