### ISSUE TITLE
No need for 3 categories

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#13]
![immagine](https://user-images.githubusercontent.com/47892201/109833555-a6e9f100-7c41-11eb-87be-0a0c759681ed.png)

La ragione di questa specifica task, è che il 99% degli utenti saranno unicamente studenti, e avere "professors" e "assistants" nella loro home, riduce la UX. 
Non ho proposto una soluzione, ma penso che la migliore sia semplicemente avere una lista di tutti i corsi, ordinati per ruolo, e magari con una icona accanto (se sei professore, c'è un cappello da prof, se sei assistente c'è una camicia, se sei studente non c'è un cazzo)

**Comment by sim55649** [comment]
solved, 
Each assignment will be printed with the icon next to it that represents whether it is professor (user with hat) / assistant (shirt) / student (user icon)
