### ISSUE TITLE
please add version number to footer

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#20]
- Makes it easier to understand if there has been a new version on dev01
- Only if not too much work
- Alternatively no need to show in footer, if it can be shown elsewhere (e.g. in account info)

![Screen Shot 2021-03-05 at 12 42 14](https://user-images.githubusercontent.com/42358482/110111270-5a70f380-7db0-11eb-941c-b0847017e82c.png)

**Comment by sim55649** [comment]
Placeholder added, at the moment we have no reference on where to get the version data, but it will be integrated as soon as available.

**Comment by sim55649** [comment]
implemented
