### ISSUE TITLE
Internal naming of HTML form fields

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#22]
When creating a new course, safari proposes to autofill my login data. I believe this is because the fields in the HTML forms for login and course creation (and possibly many more) have the same names so that Safari believes I am on the login page. See screenshot.

<img width="1223" alt="Screen Shot 2021-03-06 at 16 59 46" src="https://user-images.githubusercontent.com/42358482/110212871-bc5b5700-7e9d-11eb-9f79-d59d28cb2fb2.png">

**Comment by sim55649** [comment]
fixed in next version
