### ISSUE TITLE
assignment view, professor (montep@usi.ch) inserted in list of students

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#33]
![immagine](https://user-images.githubusercontent.com/47892201/110642430-50396580-81b3-11eb-8aec-4ca16b6d437f.png)

**Comment by rgsax** [comment]
the list is not of students!
That is th list of total submissions (professors, assistants and students)

**Comment by montemurroPaolo** [comment]
The issue is exactly that...
It makes more sense just to show student submissions to avoid confusion.

we'll think where to put assistant and professor solution afterwards. Ty! :)

**Comment by rgsax** [comment]
This can be implemented but this issue actually is not an issue
