### ISSUE TITLE
Feature request: solution template

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#40]
This is a v1 (not v2) feature request.
When creating a new assignment, add the possibility to upload an optional 4th file called template.R.
If present, this file should be pre-loaded into the student editor (and possibly also be available for download).

The template.R file would mostly consist of comments only and could look like this 

```
# Ex 1: create a vector called a with integer numbers from 1 to 10

# Ex 2: calculate average and standard deviation of data
data <- c(2,4,1,5,6,3,4,5,7,8,8)
```

**Comment by montemurroPaolo** [comment]
partiallly solved

**Comment by rgsax** [comment]
fixed by url encoding and then decoding the template in Javascript
