### ISSUE TITLE
strange message when I enter the time frame of an assignment

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#43]
Just after clicking Apply I get ...

<img width="931" alt="Screen Shot 2021-03-12 at 00 58 12" src="https://user-images.githubusercontent.com/42358482/110871155-245ed280-82ce-11eb-9c87-e62daf7494c7.png">

**Comment by rgsax** [comment]
The problem was due to a debugging session not completely dismounted after the commit. The "alert" function should be already  removed in the next commits
