### ISSUE TITLE
submission of homework from editor broken

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#44]
<img width="1195" alt="Screen Shot 2021-03-12 at 01 00 37" src="https://user-images.githubusercontent.com/42358482/110871290-68ea6e00-82ce-11eb-9423-780241196e0b.png">

**Comment by gruberpeter** [comment]
Same for submission from file

**Comment by montemurroPaolo** [comment]
I recreated the course, and uploaded a solution. Did not crash. Which file did you upload?
