### ISSUE TITLE
Editor not working properly on server. Maybe encodings?

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#48]
![immagine](https://user-images.githubusercontent.com/47892201/111045082-82b1bf80-844c-11eb-9912-f2f206a2904a.png)

**Comment by rgsax** [comment]
Can you explain in detail what is wrong?

**Comment by rgsax** [comment]
now I see the problem. There are some not url decoded characters

**Comment by rgsax** [comment]
It seems that decodeURI of Javascript is not working properly. The bug is now fixed with the use of the function decodeURIComponent
