### ISSUE TITLE
Duration bar in tables: either remove it or make it work

### ISSUE THREAD

**Issue by montemurroPaolo** [montemurroPaolo/django_autograder#51]

**Comment by sim55649** [comment]
the problem is the formula
![immagine](https://user-images.githubusercontent.com/64262053/111072318-5b093880-84da-11eb-8db2-764e1eae767f.png)

nothing to do with front end

**Comment by sim55649** [comment]
@montemurroPaolo

**Comment by montemurroPaolo** [comment]
The famous get_duration... Then let's remove it and will implement in v2

Il 14 mar 2021 15:34, sim55649 ***@***.***> ha scritto:

@montemurroPaolo<https://github.com/montemurroPaolo>

**Comment by sim55649** [comment]
it's actually very simple, I just can't figure out what the purpose is. I had intended that duration as the time left to deliver the assignment, but I don't know if I understood correctly. however, if that were the goal, a simple formula would suffice.

**Comment by montemurroPaolo** [comment]
The purpose is to have something like this, where the first date is the start of the assignment, and the last date is the due time.

![immagine](https://user-images.githubusercontent.com/47892201/111079461-666c5c00-84fa-11eb-92c1-d980bf719351.png)

**Comment by sim55649** [comment]
the formula then makes no sense because it does not take into account the difference with the current day .. it definitely needs to be revised, but it is simply a formula problem.

**Comment by sim55649** [comment]
Fixed
